# Generated by Django 5.2.12 on 2026-04-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_labtesttype_result_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtestorder',
            name='status',
            field=models.CharField(choices=[('waiting_for_sample', 'Waiting for Sample'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting_for_sample', max_length=20),
        ),
    ]
