"""
Django settings for clinical_backend project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*3bg5opnov4^k9rn68w&m8ijj!$h(gtkvrf0*%4y&paof66usw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
]


# Application definition



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'clinical_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'clinical_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# clinic_backend/settings.py
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'clinic',
]



REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ]
}

# BioPortal (NCBO) API key for ontology search
BIOPORTAL_API_KEY = os.getenv("BIOPORTAL_API_KEY", "3278cea4-ec5f-472e-850e-575d7981077f")

# CORS settings (dev)
# Expo web may choose different localhost ports (8081, 8082, ...)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8081",
    "http://localhost:8082",
    "http://localhost:19000",
    "http://localhost:19006",
]

# Also allow any localhost/127.0.0.1 port in development
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http://localhost(?::\d+)?$",
    r"^http://127\.0\.0\.1(?::\d+)?$",
]

# For development - allow all origins
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Clinic -> Lab patient profile sync
LAB_PATIENT_SYNC_ENDPOINT = os.getenv(
    "LAB_PATIENT_SYNC_ENDPOINT",
    "http://127.0.0.1:8001/api/v1/integration/clinic/patients/upsert"
).strip()
LAB_PATIENT_SYNC_TOKEN = os.getenv("LAB_PATIENT_SYNC_TOKEN", "").strip()
LAB_ORDER_INGEST_ENDPOINT = os.getenv(
    "LAB_ORDER_INGEST_ENDPOINT",
    "http://127.0.0.1:8001/api/v1/integration/clinic/lab-orders/ingest"
).strip()
LAB_ORDER_INGEST_TOKEN = os.getenv("LAB_ORDER_INGEST_TOKEN", "").strip()
LAB_INSURANCE_SYNC_ENDPOINT = os.getenv(
    "LAB_INSURANCE_SYNC_ENDPOINT",
    "http://127.0.0.1:8001/api/v1/integration/clinic/insurance-providers/upsert"
).strip()
LAB_INSURANCE_SYNC_TOKEN = os.getenv("LAB_INSURANCE_SYNC_TOKEN", "").strip()
LAB_CATALOG_ENDPOINT = os.getenv(
    "LAB_CATALOG_ENDPOINT",
    "http://127.0.0.1:8001/api/v1/integration/catalog"
).strip()
LAB_CATALOG_TOKEN = os.getenv("LAB_CATALOG_TOKEN", "").strip()

# Clinic -> Pharmacy prescription dispatch (FHIR MedicationRequest import)
PHARMACY_FHIR_ENDPOINT = os.getenv(
    "PHARMACY_FHIR_ENDPOINT",
    "http://127.0.0.1:8001/fhir/MedicationRequest/$import/"
).strip()
PHARMACY_FHIR_TOKEN = os.getenv("PHARMACY_FHIR_TOKEN", "").strip()
PHARMACY_CATALOG_ENDPOINT = os.getenv(
    "PHARMACY_CATALOG_ENDPOINT",
    "http://127.0.0.1:8001/api/v1/integration/pharmacy-medications"
).strip()
