# Generated by Django 5.2.12 on 2026-03-17 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSupplyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=40)),
                ('item_name', models.CharField(max_length=120)),
                ('quantity', models.IntegerField(default=0)),
                ('priority', models.CharField(default='Normal', max_length=20)),
                ('status', models.CharField(default='Requested', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('requested_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_requests', to='pharmacy.druginventory')),
            ],
        ),
    ]
