# Generated by Django 5.2.13 on 2026-04-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_clinic_supply_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='druginventory',
            name='barcode',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='druginventory',
            name='batch_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='druginventory',
            name='category',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='druginventory',
            name='controlled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='druginventory',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='druginventory',
            name='supplier',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
