# Generated by Django 5.2.13 on 2026-04-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_druginventory_barcode_druginventory_batch_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyorder',
            name='status',
            field=models.CharField(default='New', max_length=30),
        ),
    ]
