# Generated by Django 5.2.13 on 2026-04-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_invoice_order_pharmacyorder_prepared_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyorder',
            name='stock_deducted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
