# Generated by Django 5.2.13 on 2026-04-25 20:30

from django.db import migrations, models
import django.db.models.deletion


def backfill_products_and_lots(apps, schema_editor):
    DrugInventory = apps.get_model('pharmacy', 'DrugInventory')
    MedicineProduct = apps.get_model('pharmacy', 'MedicineProduct')
    StockLot = apps.get_model('pharmacy', 'StockLot')
    StockMovement = apps.get_model('pharmacy', 'StockMovement')

    for inventory in DrugInventory.objects.all():
        product, _ = MedicineProduct.objects.get_or_create(
            sku=inventory.sku,
            defaults={
                'name': inventory.name,
                'category': inventory.category,
                'barcode': inventory.barcode,
                'supplier': inventory.supplier,
                'low_stock_threshold': inventory.low_stock_threshold,
                'default_price': inventory.price,
                'controlled': inventory.controlled,
            },
        )
        MedicineProduct.objects.filter(pk=product.pk).update(
            name=inventory.name,
            category=inventory.category,
            barcode=inventory.barcode,
            supplier=inventory.supplier,
            low_stock_threshold=inventory.low_stock_threshold,
            default_price=inventory.price,
            controlled=inventory.controlled,
        )
        DrugInventory.objects.filter(pk=inventory.pk).update(product=product)

        lot, created = StockLot.objects.get_or_create(
            product=product,
            is_primary_snapshot=True,
            defaults={
                'lot_number': inventory.batch_number,
                'expiry_date': inventory.expiry_date,
                'supplier': inventory.supplier,
                'barcode': inventory.barcode,
                'quantity_received': inventory.quantity,
                'quantity_on_hand': inventory.quantity,
                'unit_cost': inventory.price,
            },
        )
        if not created:
            StockLot.objects.filter(pk=lot.pk).update(
                lot_number=inventory.batch_number,
                expiry_date=inventory.expiry_date,
                supplier=inventory.supplier,
                barcode=inventory.barcode,
                quantity_received=max(lot.quantity_received, inventory.quantity),
                quantity_on_hand=inventory.quantity,
                unit_cost=inventory.price,
            )

        if inventory.quantity:
            StockMovement.objects.get_or_create(
                product=product,
                lot=lot,
                movement_type='MIGRATION',
                quantity=inventory.quantity,
                balance_after=inventory.quantity,
                reference=f'legacy-inventory:{inventory.pk}',
                defaults={
                    'notes': 'Initial stock snapshot migrated from DrugInventory.',
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_pharmacyorder_stock_deducted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('barcode', models.CharField(blank=True, max_length=80)),
                ('supplier', models.CharField(blank=True, max_length=120)),
                ('low_stock_threshold', models.IntegerField(default=10)),
                ('default_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('controlled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='druginventory',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_snapshot', to='pharmacy.medicineproduct'),
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(blank=True, max_length=60)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=120)),
                ('barcode', models.CharField(blank=True, max_length=80)),
                ('quantity_received', models.IntegerField(default=0)),
                ('quantity_on_hand', models.IntegerField(default=0)),
                ('quantity_reserved', models.IntegerField(default=0)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_primary_snapshot', models.BooleanField(default=False)),
                ('is_recalled', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_lots', to='pharmacy.medicineproduct')),
            ],
            options={
                'ordering': ['expiry_date', 'lot_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('RECEIPT', 'Receipt'), ('RESERVE', 'Reserve'), ('RELEASE', 'Release'), ('DISPENSE', 'Dispense'), ('RETURN', 'Return'), ('ADJUSTMENT', 'Adjustment'), ('RECALL', 'Recall'), ('FULFILLMENT', 'Fulfillment'), ('MIGRATION', 'Migration')], max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('balance_after', models.IntegerField(default=0)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='pharmacy.stocklot')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='pharmacy.medicineproduct')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RunPython(backfill_products_and_lots, migrations.RunPython.noop),
    ]
