# Generated by Django 5.2.13 on 2026-04-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_medicineproduct_stocklot_stockmovement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyorder',
            name='dispensed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacyorder',
            name='stock_reserved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
