# Generated by Codex on 2026-05-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_patient_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='external_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='external_system',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddConstraint(
            model_name='prescription',
            constraint=models.UniqueConstraint(
                condition=models.Q(('external_id__isnull', False)),
                fields=('external_system', 'external_id'),
                name='unique_external_prescription',
            ),
        ),
    ]
